version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/paper" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/velocity" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/common" # Location of package manifests
    schedule:
      interval: "weekly"
